version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: invoice-system-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: invoice_system
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - invoice-system-network

  mongodb:
    image: mongo:latest
    container_name: invoice-system-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: invoice-system
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - invoice-system-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: invoice-system-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - invoice-system-network

networks:
  invoice-system-network:
    driver: bridge

volumes:
  postgres-data:
  mongodb-data:
